### ISSUE TITLE
chart-histogram-0.4.5 build failure

### ISSUE THREAD

**Issue by peti** [bgamari/chart-histogram#3]
Citing from http://hydra.cryp.to/build/785382/log/raw:

    Graphics/Rendering/Chart/Plot/Histogram.hs:73:19:
        Ambiguous occurrence ‘PlotHist’
        It could refer to either ‘Graphics.Rendering.Chart.Plot.Histogram.PlotHist’,
                                 defined at Graphics/Rendering/Chart/Plot/Histogram.hs:39:1
                              or ‘Graphics.Rendering.Chart.PlotHist’,
                                 imported from ‘Graphics.Rendering.Chart’ at Graphics/Rendering/Chart/Plot/Histogram.hs:30:1-31
                                 (and originally defined in ‘Graphics.Rendering.Chart.Plot.Histogram’)

**Comment by bgamari** [comment]
@peti ahh yes, it seems that `Chart-1.4` was finally released. As of 1.4 this functionality is shipped with `Chart` itself. I've marked `chart-histogram` as deprecated on Hackage although there may be a bit of a bumpy transition while dependency lists are updated.

**Comment by bgamari** [comment]
@peti I have released `chart-histogram-1.0.0` which simply reexports the appropriate modules from `Chart` to ease the transition.

**Comment by peti** [comment]
Very cool, thank you.
